- name: Install PostgreSQL
      hosts: all
      vars:
        ansible_python_interpreter: /usr/bin/python3 # Or the correct path
      tasks:
        - name: Install postgresql
          ansible.builtin.apt:
            name: postgresql
            state: present
