---
- name: Execute multiple shell commands
  hosts: all
  tasks:
    - name: Run a series of commands
      shell: |
        echo "Starting script..."
        su - postgres
        psql 
        \l
       
        echo "Script finished."
      register: output
    - debug: 
          var: output.stdout_lines
    
