---
- name: Execute multiple shell commands
  hosts: all
  tasks:
    - name: Create postgres user for my app
      postgresql_user:
        name: "myappuser"
        password: "supersecretpassword"
    - debug: 
          var: output.stdout_lines
