---
- name: Create Progres user &
  hosts: all
  gather_facts: "{{ ANSIBLE_GATHERING }}"
  vars: 
    dbname: "{{ DB_NAME }}"
    dbpass: "{{ DB_PASS }}"
  
  tasks:
    - name: Create postgres user for progress
      become: yes
      become_user: postgres
      postgresql_user:
        name: "{{ dbname }}"
        password: "{{ dbpass }}"
    - name: memastikan role sudah dibuat
      shell: "\du"
      register: output
    - debug: 
          var: output.stdout_lines
