---
- name: Using a REST API
  become: false
  hosts: all
  gather_facts: false
  tasks:
    - debug:
        msg: “Let’s call an API”

    - name: Everyone loves a good Chuck Norris joke
      uri:
        url: https://api.chucknorris.io/jokes/random
        method: GET
      register: results

    - debug:
        var: results.json.value
