---
  - name: "Testing Ports"
    hosts: all
    vars:
      ports: 
        - 22
        - 80
        - 443
    tasks:
    - name: "Test Connection Telnet"
      shell: "telnet 192.168.59.133 {{ item }}"
      register: shell_output
      loop: "{{ ports }}"
      
    - name: Debug output of shell command
      ansible.builtin.debug:
        msg: "Output for {{ item }}: {{ shell_output.results[loop_index].stdout }}"
      loop: "{{ shell_output.results }}"
      loop_control:
        index_var: loop_index

   
