---
  - name: "Testing Ports"
    hosts: all
    vars:
      ports: 
        - 22
        - 80
        - 443
    tasks:
    - name: "Test Connection Telnet"
      ansible.builtin.shell: "telnet {{ inventory_hostname  }} {{ port }}"
      register: msg
      loop: "{{ ports }}"

      #ansible.builtin.debug:: 
      #  msg: "telnet {{ inventory_hostname  }} {{ port }}"
      
