- hosts: webserver
  become: true
  tasks:
    - name: Stop service httpd, if started
      ansible.builtin.service:
         name: nginx
         state: stopped
    - name: remove nginx
      apt:
        name: nginx
        state: absent
        autoremove: yes
