---
  - name: "Playing kubernetes with Ansible."
    hosts: all
    tasks:
    - name: "kubernetes get nodes"
      shell: "kubectl get nodes"
      register: "output"
    - debug: var=output.stdout_lines
