---
  - name: "Playing kubernetes with Ansible."
    hosts: all
    tasks:
    - name: "kubernetes get pods"
      shell: "kubectl get pod -o wide --all-namespaces"
      register: "output-keluaran"
    - name: Check result
      debug:
        msg: "Result of service configuration: {{ output-keluaran }}"
     # when: result is failed
      
    - name: "kubernetes get nodes"
      shell: "kubectl get nodes"
      
      register: "output"
    - debug: var=output.stdout_lines
