---
- name: Create Progres user &
  hosts: all
  gather_facts: "{{ ANSIBLE_GATHERING }}"
  vars: 
    dbrole: "{{ DB_ROLE }}"
    dbpass: "{{ DB_PASS }}"
  
  tasks:
    - name: Create postgres user for progress
      become: yes
      become_user: postgres
      postgresql_user:
        name: "{{ dbrole }}"
        password: "{{ dbpass }}"
    - debug: 
          var: output.stdout_lines

