---
- name: Create Progres user &
  hosts: all
  gather_facts: "{{ ANSIBLE_GATHERING }}"
  vars: 
    dbrole: "{{ DB_ROLE }}"
    dbpass: "{{ DB_PASS }}"
  
  tasks:
    - name: Create postgres user for progress
      become: yes
      become_user: postgres
      postgresql_user:
        name: "{{ dbrole }}"
        password: "{{ dbpass }}"
    - name: memastikan role sudah dibuat
      ansible.builtin.shell: " \du "
        register: output
    - name: Print a message
      ansible.builtin.debug:
        msg: "This is a debug message {{ output }}"

