---
- name: Create Progres user &
  hosts: all
  gather_facts: "{{ ANSIBLE_GATHERING }}"
  vars: 
    dbrole: "{{ DB_ROLE }}"
    dbpass: "{{ DB_PASS }}"
  
  tasks:
    - name: Create postgres user for progress
      become: yes
      become_user: postgres
      postgresql_user:
        name: "{{ dbrole }}"
        password: "{{ dbpass }}"
    - name: Ensure we have access from the new user
      become: yes
      become_user: postgres
      postgresql_privs:
        db: test
        role: "{{ DB_ROLE }}"
        objs: ALL_IN_SCHEMA
        privs: SELECT,INSERT,UPDATE,DELETE
    

